:doctype: article

== Miroslav Matejovský - Curriculum Vitae

* Surname: Matejovský
* First name: Miroslav
* Date of birth: 11.07.1984
* Email: miroslav.matejovsky@gmail.com
* Phone number: +421918372392

== Work experience

* Wirecard Technologies (2014.04 - present)

  ** Software architect in VAS (2017.04 - present) +
  Introduced "Self contained systems" like architecture.
  Introduced Lagom framework with event sourcing and Cassandra with Oracle as storage.
  Introducing Kafka as broker for asynchronous messaging at the moment.

  ** Software engineer in VAS (2015.04 - 2017.03) +
  Leading VAS loyalty development team.
  Created multiple modules based on Camel and Spring boot on java 8 with focus on functional programming.
  One Akka module written in Scala.
  State persisted in DB, application layer is stateless to support horizontal scalability without need to have cluster.

  ** WebUI (2014.04 - 2015.03) +
  Ember.js application communicating with Spring MVC middle layer through REST API.
  Modern responsive multi-brand one page application for managing your payment cards.

* RWE IT Slovakia (2012.12-2014.03)

  ** ICON (2013.07-2014.03) +
  Java EE 6 (CDI, JSF, JPA, JTA, ...) application deployed to Glassfish.

  ** ZKA (Zeitkontroll-Applikation) (2013.06-2013.07) +
  Spring based web application for storing signed time relevant data.

  ** CIP (Customer Information Portal) (2012.12-2013.06) +
  Java EE web application using JSF 1.2 (richfaces 3.3), JDBC, JAX-WS and AXIS-WS.

* MoveGuides startup (2011.10-2012.03) +
  Creating server side for MoveGuides web application from scratch using Java 6, Maven, Spring, Spring MVC,
  Spring Security, Spring social, Hibernate 3. Deployed to Tomcat 7.x.

* VSL Software, a.s. (2007.07-2012.11) +
  Started as a frontend developer and moved to backend development later. Database centric applications build
  on oracle DB with proprietary technologies based on Java 6, Servlets, Portlets, JDBC. Focus in writing
  efficient SQL queries and complex business logic for health insurance companies.

== Language Experience

* Java - expert
* Javascript - advanced
* Scala - advanced
* Ruby - beginner
* Clojure - beginner
* Haskell - beginner

== Technology Experience

* Lagom
* Akka
* Camel
* Spring (MVC, boot, security, ...)
* Keycloak (OpenId Connect)
* gRPC
* REST
* ActiveMQ
* JOOQ
* SQL

== Education & Qualifications

* Oracle Certified Associate, Java SE 7 Programmer
* 2006-2007 Pavol Jozef Šafárik University in Košice +
  Computational physics including Econophysics, Simulations on lattices and Heuristic methods for finding extrema +
  2002-2005 Pavol Jozef Šafárik University in Košice +
  Physics +
  Bc.
